export const COUNTRY_LIST_REQUEST = "COUNTRY_LIST_REQUEST";
export const COUNTRY_LIST_SUCCESS = "COUNTRY_LIST_SUCCESS";
export const COUNTRY_LIST_FAIL = "COUNTRY_LIST_REQUEST";

export const COUNTRY_DATA_REQUEST = "COUNTRY_DATA_REQUEST";
export const COUNTRY_DATA_SUCCESS = "COUNTRY_DATA_SUCCESS";
export const COUNTRY_DATA_FAIL = "COUNTRY_DATA_REQUEST";
